### ISSUE TITLE
Programming Errors with CP page

### ISSUE THREAD

**Issue by kaivalyar** [OSDLabs/osdlabs.github.io#10]
There are several errors with the CP page i designed, mostly because I was in a hurry, and don't quite know web design:

- Rendering on mobile devices is incorrect (probably an asciinema issue). I tried hacking around this with min-width, but this needs review. (Probably just a simple message on mobile devices requesting the site be viewed on desktop?)
- The links are currently floated on the right ... ~~I am not sure if that is the right way to do this. needs review.~~
- I tried to get rid of the "powered by asciinema", and, even though it seems very easy, both my stylesheet edit, and my script failed to do the job. I'm unsure how to proceed with this.
- The page already has 4 videos, in one week, and thats despite omitting the vi section.... we need to find a better display for this, rather than a series of videos all on one page, one below the other. maybe a menu/contents table where user can select one video at a time, and then only that video becomes visible below....
- ???

**Comment by 0xRampey** [comment]
@kaivalyar 
1. I think this has a use case mostly for desktop users so mobile-responsiveness is not needed. Yes, a notice is the better way to go. 
2. That looks appropriate. Nothing to be done for that.
3. I honestly don't mind the footnote being there. But if you are adamant, we'll find a way to remove it.
4. Yes, if you do plan to add more videos in the near future we might have to transition to a permanent sidebar on the left that shows the contents. How does that sound?

**Comment by kaivalyar** [comment]
@prampey 
1. I tried adding a javascript alert, but it doesn't seem to work. can you please correct it?
2. OK. thanks!
3. We can ignore this for now.
4. We have to take a call on this. Is this worth pursuing from osd labs' perspective? If we do decide, then any solution (sidebar on left) is ok with me, provided the page shows only one video at a time finally.

**Comment by 0xRampey** [comment]
@kaivalyar 

1. Okay, I will look into it.
4. Absolutely. Educational material will be a hit with the faculty. Also, its a good initiative by itself. Yeah, that might be our best option. @SebastinSanty Any suggestions on the design?

**Comment by kaivalyar** [comment]
Ok, if we want to continue this, we need to have some systematic way of splitting the screencast recording between ourselves. Also, some form of feedback collection (a facebook poll?) to figure out what is working, and what isn't - to improve next weeks screencast.

**Comment by SebastinSanty** [comment]
@kaivalyar Is there anyone else who is a TA for the course (from OSDLabs or any other). We can ask them to help us. As for the faculty, I'll approach the I/C of CP if you want.

**Comment by kaivalyar** [comment]
I don't think anyone else from OSDLabs is a TA, although there are a LOT of other second years. I have the full list of TAs. I don't think we need to approach faculty for this. We can go to Neena Goveas later if we are satisfied of usefulness and quality.

**Comment by kaivalyar** [comment]
I do want to get an opinion poll running though, and figure out what changes to make in the screencast for next week. I don't think its possible to run without that. Can we get an opinion poll released on facebook today evening / tonight? Or would it be better to ask juniors to comment on our post to tell us what they would like to see changed?

**Comment by SebastinSanty** [comment]
Thats why, I think we should approach the faculty. We can announce this in the class, so that people might want to use it? (Can we talk on slack, going lengthy)

**Comment by kaivalyar** [comment]
@prampey can you please fix the alert for mobile? You can check the commit history to see what i tried and correct it.

**Comment by kaivalyar** [comment]
Also, @SebastinSanty, @prampey, to solve (4.) i'm thinking of using the design [here](http://home.kaivalyarawal.com/Settings.html) since I should be able to do it myself, hopefully. If anybody can help, it would be great.

PS: design originally from - [here](http://ringvemedia.com/traveling-ten_tips).

**Comment by kaivalyar** [comment]
Changes don't seem to be reflecting on osdlabs.org .... any ideas?
