### ISSUE TITLE
Broken link to Git slides

### ISSUE THREAD

**Issue by 0xRampey** [OSDLabs/osdlabs.github.io#11]
The link: http://osdlabs.org/sessions/git/ gives me a 404 error. 
@SebastinSanty Do you have any idea of its location?

**Comment by SebastinSanty** [comment]
It is because we have setup a permanent redirect to osdlabs.github.io which doesn't have one. We need to put a folder `sessions` in the repo.

**Comment by kaivalyar** [comment]
Who has access to the slides? Please commit the folder here?

**Comment by SebastinSanty** [comment]
I have, I'll add them asap

**Comment by kaivalyar** [comment]
This is fixed, afaik?

**Comment by 0xRampey** [comment]
Yes it is.
