### ISSUE TITLE
Multiple Branches

### ISSUE THREAD

**Issue by kaivalyar** [OSDLabs/osdlabs.github.io#4]
There are two divergent branches in this repo, currently. Can somebody please review the changes and merge them?

Also, maybe its time to move to gitter?

**Comment by SebastinSanty** [comment]
@prampey Can you review this, and make changes if necessary.

https://gitter.im/OSD-Labs

**Comment by 0xRampey** [comment]
Gitter seems to be meant for large communities, and as it is, we have Github integrations for Slack. So what gives?
@kaivalyar @SebastinSanty

**Comment by SebastinSanty** [comment]
Slack would be general talking place, whereas Gitter will be where we discuss about stuffs that goes into our projects. That way, only people interested in our projects will be there. What say?

**Comment by kaivalyar** [comment]
well, gitter is only in anticipation of further participation from beyond our immediate community - the ultimate objective of any truly open source project

while we may not have any use for this right now, we can continue using slack. gitter can be used by any outsider who, at some later point, want to contribute.

point is, its an extra channel, and we just need to keep it alive for later. if we don't use this now, no problem. lets just keep another channel.

**Comment by 0xRampey** [comment]
Okay. I'm cool with keeping it dormant for the time being.
